"""empty message

Revision ID: 2cb2e2cdb162
Revises: c635c1312ee0
Create Date: 2017-10-18 22:11:19.006928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb2e2cdb162'
down_revision = 'c635c1312ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('condition', sa.String(length=140), nullable=False))
    op.alter_column('conditions', 'pact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conditions', 'pact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('conditions', 'condition')
    # ### end Alembic commands ###
