"""empty message

Revision ID: 154ce720c31f
Revises: 4f82ec350306
Create Date: 2018-01-14 17:28:56.073488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154ce720c31f'
down_revision = '4f82ec350306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacts_users', 'conditions_passed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacts_users', sa.Column('conditions_passed', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
