"""empty message

Revision ID: 2139e8bd1157
Revises: 585419d32ab5
Create Date: 2018-01-13 11:43:01.589140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2139e8bd1157'
down_revision = '585419d32ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwordHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordHash', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
