"""empty message

Revision ID: 4f82ec350306
Revises: 58fb2e4ce3ec
Create Date: 2018-01-14 17:28:23.456575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f82ec350306'
down_revision = '58fb2e4ce3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacts_users', sa.Column('pact_signed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacts_users', 'pact_signed')
    # ### end Alembic commands ###
