"""empty message

Revision ID: 546886f304fc
Revises: 154ce720c31f
Create Date: 2018-01-14 17:29:02.666917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546886f304fc'
down_revision = '154ce720c31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacts_users', sa.Column('conditions_passed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacts_users', 'conditions_passed')
    # ### end Alembic commands ###
