"""empty message

Revision ID: 58fb2e4ce3ec
Revises: fa6cfac5d709
Create Date: 2018-01-14 17:28:06.289546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fb2e4ce3ec'
down_revision = 'fa6cfac5d709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacts_users', 'pact_signed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacts_users', sa.Column('pact_signed', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
