"""empty message

Revision ID: 635a4be7c77c
Revises: 2139e8bd1157
Create Date: 2018-01-13 11:43:24.753648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635a4be7c77c'
down_revision = '2139e8bd1157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordHash', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwordHash')
    # ### end Alembic commands ###
