"""empty message

Revision ID: e8a5a0b316cb
Revises: 80feb23bf66a
Create Date: 2018-01-14 15:06:27.995878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a5a0b316cb'
down_revision = '80feb23bf66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currentStreak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'standard',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'standard',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'currentStreak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
