"""empty message

Revision ID: fa6cfac5d709
Revises: e8a5a0b316cb
Create Date: 2018-01-14 17:22:10.785402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6cfac5d709'
down_revision = 'e8a5a0b316cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacts', sa.Column('isPublic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacts', 'isPublic')
    # ### end Alembic commands ###
